### ISSUE TITLE
ImportError: cannot import name 'field_validator' from 'pydantic'

### ISSUE THREAD

**Issue by tokk-nv** [Seeed-Projects/RAG_based_on_Jetson#1]
Tested with the latest `jetson-containers` as of today (04-22) and ran into a Python import error with `pydantic`.

**Error** 

```
oot@jao-gtc24-jp6dp:/data/RAG_based_on_Jetson# python3 main.py
Traceback (most recent call last):
  File "/data/RAG_based_on_Jetson/main.py", line 1, in <module>             
    from mlc_chat import ChatModule
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/__init__.py", line 5, in <module>
    from . import protocol, serve              
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/protocol/__init__.py", line 2, in <module>
    from . import openai_api_protocol
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/protocol/openai_api_protocol.py", line 11, in <module>
    from pydantic import BaseModel, Field, field_validator, model_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py)
root@jao-gtc24-jp6dp:/data/RAG_based_on_Jetson#
```

**Steps to reproduce**

```
git clone --depth=1 https://github.com/dusty-nv/jetson-containers jetson-containers_ss
cd jetson-containers_ss
git checkout e8c3cb53b2c6c02c20903f68020d20a92f66cc4f
```

And follow the steps as is on the README.

**Comment by LJ-Hao** [comment]
I have updated my ```mian.py``` now you can use it.
